### ISSUE TITLE
Create a better folder structure to allow more complex mods (feature request)

### ISSUE THREAD

**Issue by stiggy87** [balamod/balamod#54]
I'm trying to create a mod where I am using other lua files I have not created myself (and I'd rather not try to combine them into a single lua file in apis as to not break any other potential future mod, or flood the directory with files only my mod is dealing with).

I think a good structure for the mods is to allow the modders to have a folder structure for their mod. I understand the need for `apis`, `resources`, `localizations`, helps simplify the injection, but makes creating and testing a mod difficult. I suggest:

Each mod is its own folder structure under `mods'.

1. If people choose their own naming convention, and it conflicts with someone else's mod naming, then who wins if both are installed? 
2. It helps if people use different versions of the same lua file.
3. Standardizes how mods should be written for balamod. So the `apis`, `localizations`, `resources` should be folders under. That means all the user needs to do is provide the `buildPaths` calls themselves. 
4. Allows the use of JSON for mod info (if that's still desired), that way the injector can find the appropriate files to load. 
5. The injector code could just look for a zip file from the repos in the mod.indexes and download and open it up.

So an example flow of loading the mod:

inject function calls looks in the `mods` dir, and looks for all directories that contain a json, and if the json has the appropriate info it begins to process all sub directories in order: `apis`, `localizations`, `resources` (assuming appropriate files are there). If the json has a `dependency` key-list (if it is desired if one mod uses another), it can be used for pre-processing.

This can be even closed with a simple, "No" and I'm fine with that, just want to voice my opinion and help the community.

**Comment by UwUDev** [comment]
actually, we've already redone the mod structure for balamod 1.0.0+ *(which hasn't been released yet because I don't have much time at the moment)*.

It looks like this now
```
%appdata%/Balatro/ 
└─mods/            
  └─your_mod_id/   
    ├─main.lua     
    └─manifest.json
```

it's documented here if you want https://balamod.github.io/mod-format.html

And in your main, if you have another lua file next to it, you can call it with `require my_other_file` if the filename is `my_other_file.lua`.

you can't have 2 times the same mod because now it's loaded by `mod_id/main.lua` so you can only have one.

for example, for a sprite API it would be `mod_id/sprites/a_sheet.png`.

To tell you the truth, we've already thought of everything for 1.0.0+ but not many people have the time, i'd absolutely like to continue but i'm not on vacation yet. if you want, on the discord i've explained what you'd basically have to do to have the beginnings of a stable version with this new system.
